### ISSUE TITLE
Version 1.1.0 - Dist folder not published to NPM

### ISSUE THREAD

**Issue by gurkerl83** [platypusrex/next-merge-props#21]
It seems the dist folder specified in package.json is not published to NPM in version 1.1.0 see https://www.npmjs.com/package/next-merge-props/v/1.1.0?activeTab=code

**Comment by platypusrex** [comment]
Thank you @gurkerl83! Bad changeset config when migrating away from `tsdx`. Resolved in #22. Let me know if you notice anything else!

**Comment by gurkerl83** [comment]
It is working, thx!
